spring:
 profiles:
  active:
  - dev # 当前使用的环境
---
content: dev content 刷新看看ne  babala
spring:
 profiles: dev #开发环境
 application:
  name: hello-service
---
content: test content
spring:
 profiles: test#测试环境
 application:
  name: hello-service

